name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: 'default: index.docker.io'
        username: 'th3re'
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Upload docker image
      run: |
        IMAGE=th3re/steve-calendar-api
        TAG=$GITHUB_SHA-$GITHUB_RUN_ID
        docker build -t $IMAGE:$TAG .
        docker push $IMAGE:$TAG
        docker tag $IMAGE:$TAG $IMAGE:latest
        docker push $IMAGE:latest
